# Generated by Django 3.0.4 on 2020-03-29 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_address', models.CharField(max_length=255)),
                ('patient_phone', models.IntegerField()),
                ('patient_KTP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_name', models.CharField(max_length=50)),
                ('specialist_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=10)),
                ('doctor_address', models.CharField(max_length=100)),
                ('id_specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Specialist')),
            ],
        ),
    ]
